spring.application.name=DoctorMS
server.port=${PORT:8081}

# --- Database Connection ---
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=${DB_DDL}

spring.jpa.hibernate.ddl-auto=create
#spring.jpa.hibernate.ddl-auto=update


# --- Feign client target ---
# --- Zipkin ---
management.tracing.sampling.probability=1.0

# Inter-Service URLs
services.doctor.url=http://localhost:8081
services.patient.url=http://localhost:8082
services.therapist.url=http://localhost:8083
services.user.url=http://localhost:8086
services.api.url=http://localhost:8085


# Expose all actuator endpoints over HTTP
management.endpoints.web.exposure.include=*

# Allow access to actuator endpoints from any IP (remove or restrict in prod!)
management.endpoint.health.show-details=always
management.endpoints.web.base-path=/actuator

# Enable CORS for actuator endpoints (so you can call from browser tools)
management.endpoints.web.cors.allowed-origins=*
management.endpoints.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
management.endpoints.web.cors.allowed-headers=*

# Show all health details (not just status)
management.endpoint.health.probes.enabled=true
management.endpoint.health.show-components=always

management.health.circuitbreakers.enabled=true


# --- RabbitMQ ---
spring.rabbitmq.host=puffin.rmq2.cloudamqp.com
spring.rabbitmq.port=5671
spring.rabbitmq.username=xxdyrbyp
spring.rabbitmq.password=sMZm3gic-y-AkLzdZ-GznO_6oQOb4XSx
spring.rabbitmq.virtual-host=xxdyrbyp
spring.rabbitmq.ssl.enabled=true

spring.security.user.name=ayursutra
spring.security.user.password=1234


jwt.secretkey = ${jwt.secretkeyENV}


# Service to Service Communication
spring.security.oauth2.resourceserver.jwt.issuer-uri=${services.user.url}
service-auth.services.doctor-service.client-id=DoctorMS
service-auth.services.doctor-service.client-secret=doctor-secret-123
service-auth.services.user-service.client-id=userMS
service-auth.services.user-service.client-secret=user-secret-123
service-auth.services.patient-service.client-id=PatientMS
service-auth.services.patient-service.client-secret=patient-secret-123
service-auth.services.therapist-service.client-id=TherapistMS
service-auth.services.therapist-service.client-secret=therapist-secret-123